[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project]
name = "YuchenNN"
version = "0.0.1"

dependencies = [
]

[tool.hatch.build.targets.wheel]
packages = [ "YuchenNN" ]
